name: Update Policy Aliases

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 12 * * *'
  # Allows manual trigger from the Actions tab
  workflow_dispatch:

jobs:
  update-aliases:
    runs-on: windows-latest
    permissions:
      contents: write  # This is needed for pushing changes
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
        
    - name: Install Azure PowerShell Module
      shell: pwsh
      run: |
        Install-Module -Name Az -Force -AllowClobber -Scope CurrentUser
        
    - name: Login to Azure PowerShell
      shell: pwsh
      run: |
        $creds = '${{ secrets.AZURE_CREDENTIALS }}' | ConvertFrom-Json
        $securePassword = ConvertTo-SecureString $creds.clientSecret -AsPlainText -Force
        $credential = New-Object System.Management.Automation.PSCredential($creds.clientId, $securePassword)
        Connect-AzAccount -ServicePrincipal -Tenant $creds.tenantId -Credential $credential
        Set-AzContext -Subscription $creds.subscriptionId
        
    - name: Run PowerShell script
      shell: pwsh
      run: |
        ./src/scripts/Get_All_Aliases.ps1
        
    - name: Commit and push if changed
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add src/data/AzPolicyAliases.json
        git commit -m "Update policy aliases"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
